import { LiveblocksClientProvider } from "@/components/Liveblocks/LiveblocksClientProvider";
import type { Metadata } from "next";
import 'normalize.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LiveblocksClientProvider>
          {children}
        </LiveblocksClientProvider>
      </body>
    </html>
  );
}
